---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: api-tado
 labels:
  type: rest
  slot: smarthome
  app: api-tado
spec:
 replicas: 1
 selector:
  matchLabels:
   app: api-tado
 template:
  metadata:
   labels:
    app: api-tado
  spec:
   containers:
    - image: expovin/api.tado
      name: api-tado
      volumeMounts:
      - name: config
        mountPath: "/usr/src/app/secrets"
        readOnly: true                 
      ports: 
       - containerPort: 3000       
      env:
       - name :  PORT
         value: "3000"
       - name : TZ
         value: "Europe/Rome"
   volumes:
    - name: config
      secret:
       secretName: api-tado
---
apiVersion: v1
kind: Service
metadata:
  name: api-tado
spec:
  selector:
    app: api-tado
  ports:
    - protocol: TCP
      name : http
      port: 3000
      targetPort: 3000
