kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodata
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: mongo-local
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 500Mi