apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodata
spec:
  capacity:
    storage: 500Mi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.0.13
    path: "/dev"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-local
  labels:
    type: local  
spec:
  capacity:
    storage: 500Mi
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/media/raspyshare/mongodata/"