apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-syno
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.0.4
    path: "/volume1/k8s"